### ISSUE TITLE
Module '"knip"' has no exported member 'KnipConfig'. Did you mean to use 'import KnipConfig from "knip"' instead?

### ISSUE THREAD

**Issue by swingthrough** [webpro-nl/knip#649]
https://knip.dev/reference/dynamic-configuration

There is an example in the docs for dynamic configuration using `knip.ts` file, and the example follows with this import:
```
import type { KnipConfig } from 'knip';
```

However VSCode shows an error:
```
Module '"knip"' has no exported member 'KnipConfig'. Did you mean to use 'import KnipConfig from "knip"' instead?ts(2614)
```

![image](https://github.com/webpro/knip/assets/43108861/c99289da-fb81-47d9-bdfd-9cfcfd498471)

**Comment by swingthrough** [comment]
I just tried renaming `knip.ts` to `knip.config.ts` based on this:
https://knip.dev/overview/configuration#location

and it works.
Still, the locations list `knip.ts` first, and the example for dynamic configuration states `knip.ts` as the filename that's used.

**Comment by webpro** [comment]
Not sure how to fix that. If you look at the `package.json#types` then you'll find a matching file (`dist/index.d.ts`) that has an export named `KnipConfig`.

**Comment by chiefchief** [comment]
the same to me 
<img width="736" alt="Screenshot 2024-08-04 at 12 42 11" src="https://github.com/user-attachments/assets/08159eec-508a-4667-bf03-f892e0712c61">

**Comment by acontreras89** [comment]
@webpro the problem seems to be that TypScript will try to resolve modules from userland code before falling back to `node_modules`. If  `compilerOptions.baseUrl` is set to the root directory (`"."`), then the `import ... from 'knip'` is treated as a self-reference import.

That's also why renaming the file to `knip.config.ts` gets rid of the issue. Other possible workarounds are:

1) Make the import more specific

```ts
import type { KnipConfig } from 'knip/dist'
```

2) Instruct TypeScript on how to resolve `knip` (in `tsconfig.json`)

```json
  "baseUrl": ".",
  "paths": {
    "knip": ["node_modules/knip"]
  },
```

Although I prefer using `knip.config.ts` and I think the docs should suggest this rather than `knip.ts`, too.
