### ISSUE TITLE
Run the script only against the staged files.

### ISSUE THREAD

**Issue by hyungjunk** [webpro-nl/knip#652]
Hi, thank you for the wonderful package.

Can I run the script only for the files that are git-staged?

Currently, I am using `lint-staged` to check the validity of staged files. On top of this, I wish I could run `knip` script only for the staged files.

**Comment by webpro** [comment]
Knip is more of a project linter rather than a per-file linter. So it requires the full context of the project (this is different from e.g. ESLint or Prettier).

It's not impossible, but it would rely on the rest of the files being cached.  What you could do:

- Add the `--cache` argument to speed things up
- In a monorepo, you could add `--workspace [directory]` if the changed files are all within that workspace `directory` (which would require a script to figure that out first) to speeds things up further

There's also [`--watch`](https://knip.dev/reference/cli#--watch) which is a fun feature to see issues during development.

Over time, Knip should become faster making this experience more enjoyable.

Hope this helps :)

**Comment by webpro** [comment]
Closing this as there isn't much more Knip can do at the moment.
