### ISSUE TITLE
Path mapping configuration not respected for .json files

### ISSUE THREAD

**Issue by geigerzaehler** [webpro-nl/knip#669]
The `path` configuration works for `.js` files but not for `.json` files.

I have the following config:
```json
{
  "paths": {
    "@src/*": ["./src/*"]
  }
}
```

and the following entry point:
```js
import "@src/data.json"
```

Running knip reports an issue
```
Unlisted dependencies (1)
@src/data.json  src/index.js
```

Before v5.17 I was able to work around the problem by specifying `"ignoreDependencies": ["@src"]` but that doesn’t work anymore.

If I use `import "@src/data.js"` or `import "./data.json"` no issues are reported.

You can find a minimal production on [StackBlitz](https://stackblitz.com/edit/github-pkwe7r?file=src%2Findex.js)

**Comment by webpro** [comment]
It's odd that the workaround worked, but why not try `@src/data.json` instead? you can also try [knip-bun](https://knip.dev/reference/cli#knip-bun).

I'll look into it when I find the time.

**Comment by geigerzaehler** [comment]
> It's odd that the workaround worked

I meant `"ignoreDependencies": ["@src"]` of course, not `"src"`. (Updated in the description)

> but why not try `@src/data.json` instead?

In my actual use case I have a lot of files so I didn’t consider listing them individually. But of course using a regular expression works.

**Comment by geigerzaehler** [comment]
If you can point me to a test which I can modify to trigger the bug I can take a look myself and try to fix it.

**Comment by webpro** [comment]
Thanks feel free to take a stab at it, appreciate it.

- Might end up at this (fallback and old code) [here](https://github.com/webpro-nl/knip/blob/main/packages/knip/src/ProjectPrincipal.ts#L278-L289) because JSON is not in `extensions` [here](https://github.com/webpro-nl/knip/blob/main/packages/knip/src/typescript/resolveModuleNames.ts#L68) so I guess it won't be resolved and the import specifier looks like a package.
- Related fixtures and tests have "module-resolution-non-std" in their name.
