### ISSUE TITLE
🐛 There seems to be a false positive with config files

### ISSUE THREAD

**Issue by AlemTuzlak** [webpro-nl/knip#791]
### Prerequisites

- [X] I'm using the latest version
- [X] I've read the relevant [documentation](https://knip.dev)
- [X] I've searched for [existing issues](https://github.com/webpro-nl/knip/issues?q=is%3Aissue)
- [X] I've checked the [list of known issues](https://knip.dev/reference/known-issues)
- [X] I've read the [issue reproduction guide](https://knip.dev/guides/issue-reproduction)

### Reproduction url

https://github.com/forge42dev/Remix-Dev-Tools/pull/150

### Reproduction access

- [X] I've made sure the reproduction is publicly accessible

### Description of the issue

Hey Lars!
Hope you're well, so if you open up the url I sent and clone the PR and delete the `"tsup*.ts"` from the `ignore` list you'll get reports of unused files which are indeed used to bundle the client and server parts of RDT. They are located in the root package.json. Maybe it can help make the detection better, or maybe I missed something

**Comment by webpro** [comment]
The default tsup plugin is here: https://knip.dev/reference/plugins/tsup and you can override it by setting e.g `tsup.config: ["tsup*.ts"]`


In general, if you customize the location of a config file, that should probably also happen in Knip config. Knip tries to follow the defaults of the tool or framework as much as possible (and those defaults might change over time).


Knip has custom parsers to find _entry_ files from `package.json#scripts` and this covers a good deal of cases generally speaking, but there's no support for _config_ files yet. That's a bit different, since it has to be done in the plugin itself.

**Comment by webpro** [comment]
Doing a large refactor, which will also unlock this feature. You could try it out if you like:

```
pnpm add -D https://pkg.pr.new/knip@d288779
```

(just fyi, [what this takes inside Knip plugins](https://github.com/webpro-nl/knip/blob/feat/unlock-the-scissors/packages/knip/src/plugins/tsup/index.ts#L32-L34))

**Comment by webpro** [comment]
Going to close with the release of v5.34.0

**Comment by AlemTuzlak** [comment]
indeed fixed
