### ISSUE TITLE
🐛 commitlint plugin not enabled by all relevant dependencies

### ISSUE THREAD

**Issue by bigpopakap** [webpro-nl/knip#836]
### Prerequisites

- [X] I'm using the latest version
- [X] I've read the relevant [documentation](https://knip.dev)
- [X] I've searched for [existing issues](https://github.com/webpro-nl/knip/issues?q=is%3Aissue)
- [X] I've checked the [list of known issues](https://knip.dev/reference/known-issues)
- [X] I've read the [issue reproduction guide](https://knip.dev/guides/issue-reproduction)

### Reproduction url

https://stackblitz.com/edit/github-hfa3yv?file=commitlint.config.ts

Note that it flags `commitlint.config.ts` as an unused file, and the 3 dependencies as unused.
All these issues are fixed by manually enabling the plugin with `commitlint: true` in the Knip config.

### Reproduction access

- [X] I've made sure the reproduction is publicly accessible

### Description of the issue

Currently, the [commitlint plugin only uses `@commitlint/cli` to be enabled](https://knip.dev/reference/plugins/commitlint)

It should also probably also use the `commitlint` package itself

In my project, I don't use `@commitlint/cli`, but I _do_ use commitlint (in a git hook and on CI with the [commitlint orb](https://circleci.com/developer/orbs/orb/conventional-changelog/commitlint)), and I have these in my `devDependencies`
```json
  "devDependencies": {
    "@commitlint/config-conventional": "19.5.0",
    "@commitlint/types": "19.5.0",
    "commitlint": "19.5.0",
  },
```

**Comment by webpro** [comment]
That doesn't like an actual reproduction? Any chance you could fix that up?

**Comment by webpro** [comment]
Thanks for the updates. Enabler is (only) `@commitlint/cli` because of install instructions at https://commitlint.js.org/guides/getting-started.html, I agree with all you're saying here.

The type of detection you show is too smart/custom indeed imho (I like how basically all plugins use the same simple mechanism that seems to hold up fairly well).

Question remains, should `commitlint` be added as an enabler. No one else has filed an issue or shown a similar use case, so I'm leaning towards keeping it as it is (i.e. requiring a `commitlint: true` on user's end), but happy to hear your thoughts on this.

**Comment by webpro** [comment]
Thanks a lot, @bigpopakap. Glad we came to the same conclusion.
